#ifndef DEFINES_H_HEADER_GUARD
#define DEFINES_H_HEADER_GUARD

#define LOCO_DEFAULT_RESOURCE_PATH "resources/"
#define LOCO_COMMON_RESOURCE_PATH "common/"

#define LOCO_EXTENTION_LENGTH 8
#define LOCO_PATH_LENGTH 256

#define LOCO_MURMUR_HASH_SEED 12345678




#endif // DEFINES_H_HEADER_GUARD

